=== Aylinap/XMLDT/examenultimo/valivoluntario.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="voluntarios">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="voluntario" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="nombreTipo"></xs:element>
                            <xs:element name="apellido"></xs:element>
                            <xs:element name="fecha_nacimiento" type="xs:date"></xs:element>
                            <xs:element name="genero">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="Mujer"></xs:enumeration>
                                        <xs:enumeration value="Hombre"></xs:enumeration>
                                        <xs:enumeration value="No_binario"></xs:enumeration>
                                        <xs:enumeration value="Otros"></xs:enumeration>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="habilidades" type="xs:string"></xs:element>
                            <xs:element name="correo">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <!-- buscar si esta bien esto??-->
                                        <!-- https://stackoverflow.com/questions/2147780/how-to-validate-an-email-id-in-xml-schema-->
                                        <xs:pattern value="[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}"></xs:pattern>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="horas_servicio" type="xs:positiveInteger" minOccurs="0"></xs:element>
                            <xs:element name="proyectos" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="proyecto" type="proyectoTipo" minOccurs="0" maxOccurs="unbounded"></xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="disponibilidad">
                                <xs:complexType>
                                    <xs:choice>
                                        <xs:element name="dia" type="xs:string" minOccurs="0" maxOccurs="7"></xs:element>
                                        <xs:element name="mes" type="xs:string" minOccurs="0" maxOccurs="12"></xs:element>
                                    </xs:choice>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="tipo" use="required">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="diario"></xs:enumeration>
                                    <xs:enumeration value="largaEstancia"></xs:enumeration>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
<!--declaraciones apartadas -->
     <!-- tipo restriccion nombre-->
     <xs:simpleType name="nombreTipo">
        <xs:restriction base="xs:string">
            <xs:minLength value="1"></xs:minLength>
            <xs:maxLength value="250"></xs:maxLength>
        </xs:restriction>
    </xs:simpleType>
    <!-- restriccion para el proyecto  -->
    <xs:simpleType name="proyectoTipo">
        <xs:restriction base="xs:string">
            <xs:pattern value="[P][0-9]{3}"></xs:pattern>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== Aylinap/XMLDT/examenultimo/voluntario.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="transfo.xsl"?>
<voluntarios xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="valivoluntario.xsd">
        <voluntario tipo="diario">
            <nombre>Valentin</nombre>
            <apellido>xxxx</apellido>
            <fecha_nacimiento>1990-05-15</fecha_nacimiento>
            <genero>Hombre</genero>
            <habilidades>Ayuda comunitaria</habilidades>
            <correo>valentin@gmail.com</correo>
            <horas_servicio>60</horas_servicio>
            <proyectos>
                <proyecto>P232</proyecto>
                <proyecto>P432</proyecto>
            </proyectos>
            <disponibilidad>
                <dia>Lunes</dia>
                <dia>Miércoles</dia>
                <dia>Viernes</dia>
            </disponibilidad>
        </voluntario>
        <voluntario tipo="largaEstancia">
            <nombre>Juan</nombre>
            <apellido>xxxx</apellido>
            <fecha_nacimiento>1997-05-15</fecha_nacimiento>
            <genero>Hombre</genero>
            <habilidades>Ayuda comunitaria</habilidades>
            <correo>juan@gmail.com</correo>
            <horas_servicio>30</horas_servicio>
            <proyectos>
                <proyecto>P001</proyecto>
                <proyecto>P003</proyecto>
            </proyectos>
            <disponibilidad>
                <mes>Marzo</mes>
                <mes>Abril</mes>
                <mes>Agosto</mes>
            </disponibilidad>
        </voluntario>
        <voluntario tipo="largaEstancia">
            <nombre>Valentina</nombre>
            <apellido>xxxx</apellido>
            <fecha_nacimiento>1999-05-15</fecha_nacimiento>
            <genero>Mujer</genero>
            <habilidades>Ayuda comunitaria</habilidades>
            <correo>valentin@gmail.com</correo>
            <horas_servicio>30</horas_servicio>
            <proyectos>
                <proyecto>P001</proyecto>
                <proyecto>P456</proyecto>
            </proyectos>
            <disponibilidad>
                <dia>Lunes</dia>
                <dia>Miércoles</dia>
                <dia>Viernes</dia>
            </disponibilidad>
        </voluntario>
        <voluntario tipo="diario">
            <nombre>miguel</nombre>
            <apellido>xxxx</apellido>
            <fecha_nacimiento>1991-05-15</fecha_nacimiento>
            <genero>Hombre</genero>
            <habilidades>Ayuda Sanidad</habilidades>
            <correo>miguel@gmail.com</correo>
            <horas_servicio>54</horas_servicio>
            <proyectos>
                <proyecto>P234</proyecto>
                <proyecto>P345</proyecto>
            </proyectos>
            <disponibilidad>
                <dia>Lunes</dia>
                <dia>Jueves</dia>
                <dia>Viernes</dia>
            </disponibilidad>
        </voluntario>
</voluntarios>
