=== Aylinap/XMLDT/EjerciciosXMLVARIOS/validacion1.xsd
<?xml version="1.0" encoding="UTF-8"?>

<!-- para enlazar este archivo a un xml se pone 
     
      <?xml version="1.0"?>
        <elemento_raiz
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance "
        xsi:noNamespaceSchemaLocation ="enlace_fichero.xsd">
--> 
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="personas">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="persona">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string"></xs:element>
                            <xs:element name="apellido" type="xs:string"></xs:element>
                            <xs:element name="direccion" type="xs:string"></xs:element>
                            <xs:element name="fecha" type="xs:date"></xs:element>
                            <xs:element name="poblacion" type="xs:string"></xs:element>
                            <xs:element name="provincia" type="xs:string"></xs:element>
                            <xs:element name="codigoPostal" type="xs:integer"></xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Aylinap/XMLDT/EjerciciosXMLVARIOS/personas2shema.xml
<?xml version="1.0" encoding="UTF-8"?>

<personas
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance "
xsi:noNamespaceSchemaLocation ="validacion1.xsd">

    <persona>
        <nombre>Ayline</nombre>
        <apellido>Ponce</apellido>
        <direccion>Pintore Kalea 9, 3E</direccion>
        <fecha>17/08/1995</fecha>
        <poblacion>Lasarte-Oria</poblacion>
        <provincia>Gipuzkoa</provincia>
        <codigoPostal>20160</codigoPostal>
    </persona>
    <persona>
        <nombre>Valentin</nombre>
        <apellido>Ponce</apellido>
        <direccion>Pintore Kalea 9,3E</direccion>
        <fecha>17/02/2023</fecha>
        <poblacion>Lasarte-Oria</poblacion>
        <provincia>Gipuzkoa</provincia>
        <codigoPostal>20160</codigoPostal>
    </persona>
</personas>
