=== Aylinap/XMLDT/EjercicioEntregaSemanaSanta/videos2.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="videos">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="video" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="titulo" type="xs:string"/><!-- en titulo me falto colocarle el tamaño que era entre 0-250-->
                            <xs:element name="tipo">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="Serie"/>
                                        <xs:enumeration value="Película"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="genero" minOccurs="0">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="Drama"/>
                                        <xs:enumeration value="Comedia"/>
                                        <xs:enumeration value="Ciencia Ficción"/>
                                        <xs:enumeration value="Terror"/>
                                        <xs:enumeration value="Acción"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="fecha_de_estreno" type="xs:date"/>
                            <xs:choice><!-- para decir si es uno u otro, serie o pelicula-->
                                <xs:element name="pelicula">
                                    <xs:complexType>
                                        <xs:sequence>
                                            <xs:element name="duracion" type="tipoDuracion"/>
                                            <xs:element name="director" type="xs:string"/>
                                        </xs:sequence>
                                    </xs:complexType>
                                </xs:element>
                                <xs:element name="serie">
                                    <xs:complexType>
                                        <xs:sequence>
                                            <xs:element name="temporada" type="xs:integer"/>
                                            <xs:element name="capitulos">
                                                <xs:complexType>
                                                    <xs:sequence>
                                                        <xs:element name="capitulo" maxOccurs="unbounded">
                                                            <xs:complexType>
                                                                <xs:sequence>
                                                                    <xs:element name="titulo" type="xs:string"/>
                                                                    <xs:element name="temporada" type="xs:integer"/>
                                                                    <xs:element name="orden" type="xs:integer"/>
                                                                    <xs:element name="duracion" type="tipoDuracion"/>
                                                                </xs:sequence>
                                                            </xs:complexType>
                                                        </xs:element>
                                                    </xs:sequence>
                                                </xs:complexType>
                                            </xs:element>
                                        </xs:sequence>
                                    </xs:complexType>
                                </xs:element>
                            </xs:choice>
                        </xs:sequence>
                        <xs:attribute name="precio" type="xs:decimal" use="required"/>
                        <xs:attribute name="codigo">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:pattern value="[P/S][0-9]{2}"/><!--[0-9][0-9] tambien se puede hacer asi, en cambio del {2}-->
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- Duracion definido aparte -->
    <xs:simpleType name="tipoDuracion">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="1"/>
            <xs:maxInclusive value="300"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== Aylinap/XMLDT/EjercicioEntregaSemanaSanta/videos2.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="videos2.xsl"?>
<videos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="videos2.xsd">
    <video precio="3.99" codigo="S45">
        <titulo>Stranger Things</titulo>
        <tipo>Serie</tipo>
        <genero>Ciencia Ficción</genero>
        <fecha_de_estreno>2016-07-15</fecha_de_estreno>
        <serie>
            <temporada>1</temporada>
            <capitulos>
                <capitulo>
                    <titulo>Capitulo 1: El inicio</titulo>
                    <temporada>1</temporada>
                    <orden>1</orden>
                    <duracion>50</duracion>
                </capitulo>
                <capitulo>
                    <titulo>Capitulo 2: La desaparicion de Will</titulo>
                    <temporada>1</temporada>
                    <orden>2</orden>
                    <duracion>55</duracion>
                </capitulo>
                <capitulo>
                    <titulo>Capitulo 3: La extraña desaparición de Barb</titulo>
                    <temporada>1</temporada>
                    <orden>3</orden>
                    <duracion>48</duracion>
                </capitulo>
                <capitulo>
                    <titulo>Capitulo 4: Los experimentos del laboratorio</titulo>
                    <temporada>1</temporada>
                    <orden>4</orden>
                    <duracion>52</duracion>
                </capitulo>
                <capitulo>
                    <titulo>Capitulo 5: El encuentro con el Demogorgon</titulo>
                    <temporada>1</temporada>
                    <orden>5</orden>
                    <duracion>53</duracion>
                </capitulo>
            </capitulos>
        </serie>
    </video>
    <video precio="5.49" codigo="S50">
        <titulo>Supernatural</titulo>
        <tipo>Serie</tipo>
        <genero>Terror</genero>
        <fecha_de_estreno>2005-09-13</fecha_de_estreno>
        <serie>
            <temporada>1</temporada>
            <capitulos>
                <capitulo>
                    <titulo>Capitulo 1: El comienzo</titulo>
                    <temporada>1</temporada>
                    <orden>1</orden>
                    <duracion>45</duracion>
                </capitulo>
                <capitulo>
                    <titulo>Capitulo 2: La casa encantada</titulo>
                    <temporada>1</temporada>
                    <orden>2</orden>
                    <duracion>50</duracion>
                </capitulo>
                <capitulo>
                    <titulo>Capitulo 3: El exorcismo</titulo>
                    <temporada>1</temporada>
                    <orden>3</orden>
                    <duracion>48</duracion>
                </capitulo>
                <capitulo>
                    <titulo>Capitulo 4: El pacto</titulo>
                    <temporada>1</temporada>
                    <orden>4</orden>
                    <duracion>52</duracion>
                </capitulo>
            </capitulos>
        </serie>
    </video>    
    <video precio="9.99" codigo="P10">
        <titulo>Interstellar</titulo>
        <tipo>Película</tipo>
        <genero>Ciencia Ficción</genero>
        <fecha_de_estreno>2014-11-07</fecha_de_estreno>
        <pelicula>
            <duracion>169</duracion>
            <director>Christopher Nolan</director>
        </pelicula>
    </video>
    <video precio="8.99" codigo="P30">
        <titulo>Blade Runner 2049</titulo>
        <tipo>Película</tipo>
        <genero>Ciencia Ficción</genero>
        <fecha_de_estreno>2017-10-06</fecha_de_estreno>
        <pelicula>
            <duracion>163</duracion>
            <director>Denis Villeneuve</director>
        </pelicula>
    </video>
</videos>
